## PyTorch Fundamentals Part A

- A PyTorch tensor is a multi-dimensional array (0D to nD) that contains elements of a single data type (e.g., integers, floats). 
- Tensors are used to represent scalars, vectors, matrices, or higher-dimensional data and are optimized for mathematical operations, automatic differentiation, and GPU computation

In [2]:
import torch
torch.__version__

'2.6.0+cu126'

### Multi-dimensional

In [3]:
# 0D: Scalar 
x= torch.tensor(5)
x

tensor(5)

In [4]:
x.ndim

0

In [5]:
x.shape

torch.Size([])

In [6]:
x.item()

5

In [7]:
# 1D: Vector 
x=torch.tensor([1, 2, 3])
x

tensor([1, 2, 3])

In [8]:
x.ndim

1

In [9]:
# shape is a tuple, although looks like a list
x.shape

torch.Size([3])

In [10]:
# 2D Matrix
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR.size()

torch.Size([1, 3, 3])

In [17]:
torch.tensor([[[1, 2, 3],
                        [3, 6, 9]]]).reshape(3,2)

tensor([[1, 2],
        [3, 3],
        [6, 9]])

In [18]:
torch.tensor([[[1, 2, 3],
                        [3, 6, 9]]]).reshape(-1,1)

tensor([[1],
        [2],
        [3],
        [3],
        [6],
        [9]])

In [19]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]], dtype=torch.float32)
TENSOR

tensor([[[1., 2., 3.],
         [3., 6., 9.],
         [2., 4., 5.]]])

In [20]:
TENSOR.dtype

torch.float32

In [21]:
y = torch.rand(2, 2)
x = torch.rand(2, 2)
x, y

(tensor([[0.9019, 0.8531],
         [0.9996, 0.5826]]),
 tensor([[0.0682, 0.6102],
         [0.5610, 0.0305]]))

### Slicing

In [22]:
x=torch.tensor([1, 2, 3, 4, 5, 6])
x[0:2]

tensor([1, 2])

In [23]:
x=torch.tensor([1, 2, 3, 4, 5, 6])
x[:2]

tensor([1, 2])

In [24]:
x=torch.tensor([1, 2, 3, 4, 5, 6])
x[-1]

tensor(6)

In [25]:
x=torch.tensor([1, 2, 3, 4, 5, 6])
x[2:]

tensor([3, 4, 5, 6])

In [26]:
# Example 2D tensor
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Syntax: x[row_slice, column_slice]

# Slice the first two rows and the first two columns
x[:2, :2]  # tensor([[1, 2],
           #         [4, 5]])

tensor([[1, 2],
        [4, 5]])

In [27]:
# Slice the second row
x[1, :]    # tensor([4, 5, 6])

tensor([4, 5, 6])

In [28]:
# Slice the third column
x[:, 2]    # tensor([3, 6, 9])

tensor([3, 6, 9])

In [29]:
# Example 2D tensor
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Get a submatrix from row 1 to 2 (exclusive of 2), and column 1 to 3
x[1:2, 1:3]  # tensor([[5, 6]])

tensor([[5, 6]])

### sum, mean, max

In [30]:
a=torch.tensor([0, 1, 1, 1])
b=torch.tensor([1, 0, 1, 1])
a.eq(b)

tensor([False, False,  True,  True])

In [31]:
# convert tensor tensor([False, False,  True,  True]) to [0, 0, 1, 1]
a.eq(b).sum()

tensor(2)

In [32]:
torch.tensor([0, 1, 2, 3]).sum()

tensor(6)

In [54]:
y=torch.tensor([0, 1, 2, 3])
torch.sum(y)

tensor(6)

In [55]:
y=torch.tensor([0, 1, 2, 3])
torch.max(y)

tensor(3)

In [58]:
test_outputs = torch.tensor([[2.5, 0.8, 1.3],  # Sample 1
                            [0.4, 3.2, 1.9]]) # Sample 2
max_values, max_indices = torch.max(test_outputs,1)

In [59]:
max_values

tensor([2.5000, 3.2000])

In [61]:
max_indices

tensor([0, 1])

### Operations

In [33]:
x= tensor = torch.tensor([[1, 2], 
                       [3, 4]])
y= tensor = torch.tensor([[5, 6], 
                       [7, 8]])
x, y

(tensor([[1, 2],
         [3, 4]]),
 tensor([[5, 6],
         [7, 8]]))

In [34]:
x+y

tensor([[ 6,  8],
        [10, 12]])

In [35]:
z=x*y
z

tensor([[ 5, 12],
        [21, 32]])

In [36]:
# Create a tensor of values and add a number to it
# recall broadcasting rules
tensor = torch.tensor([1, 2, 3])
results= tensor + 10
results

tensor([11, 12, 13])

In [37]:
# reshaping
tensor = torch.tensor([1, 2, 3, 4, 5, 6])
tensor.view(2, 3)  # Reshape to 2x2

tensor([[1, 2, 3],
        [4, 5, 6]])

In [38]:
tensor.view(3, 2)  # Reshape to 3x2

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [39]:
x = torch.tensor([0, 1, 1, 0, 1, 0])
x == 1

tensor([False,  True,  True, False,  True, False])

In [40]:
y = torch.tensor([0, 1, 0, 0, 1, 1])
y == 0

tensor([ True, False,  True,  True, False, False])

In [41]:
(x == 1) & (y==0)

tensor([False, False,  True, False, False, False])

In [42]:
((x == 1) & (y==0)).sum()

tensor(1)

In [43]:
torch.sum(((x == 1) & (y==0)))

tensor(1)

## Comparison to NumPy Arrays
Tensors are similar to NumPy arrays but add:
- GPU support.
- Automatic differentiation (requires_grad).
 - Integration with PyTorch’s deep learning ecosystem.

In [44]:
import numpy as np
tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [45]:
numpy_array = tensor.numpy()  # To NumPy
numpy_array 

array([1, 2, 3])

In [46]:
tensor_from_numpy = torch.from_numpy(numpy_array)  # Back to tensor
tensor_from_numpy 

tensor([1, 2, 3])

### Running tensors on GPUs (and making faster computations)


In [47]:
# Check for GPU
import torch
torch.cuda.is_available()

True

In [48]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [49]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [50]:
# by default all tensors are created on the CPU,
# but you can also move them to the GPU (only if it's available )
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    x = torch.tensor([1, 2, 3])
    y = torch.tensor(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    # z = z.numpy() # not possible because numpy cannot handle GPU tenors
    # move to CPU again
    z= z.to("cpu")       # ``.to`` can also change dtype together!
    # z = z.numpy()

C:\Users\Weife\AppData\Local\Temp\ipykernel_154616\3540074575.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y = torch.tensor(x, device=device)  # directly create a tensor on GPU
