## PyTorch Fundamentals Part A

- A PyTorch tensor is a multi-dimensional array (0D to nD) that contains elements of a single data type (e.g., integers, floats). 
- Tensors are used to represent scalars, vectors, matrices, or higher-dimensional data and are optimized for mathematical operations, automatic differentiation, and GPU computation

In [48]:
import torch
torch.__version__

'2.6.0+cu126'

### Multi-dimensional

In [49]:
# 0D: Scalar 
x= torch.tensor(5)
x

tensor(5)

In [50]:
x.ndim

0

In [51]:
x.shape

torch.Size([])

In [52]:
x.item()

5

In [53]:
# 1D: Vector 
x=torch.tensor([1, 2, 3])
x

tensor([1, 2, 3])

In [54]:
x.ndim

1

In [55]:
# shape is a tuple, although looks like a list
x.shape

torch.Size([3])

In [56]:
# 2D Matrix
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [57]:
MATRIX.ndim

2

In [58]:
MATRIX.shape

torch.Size([2, 2])

In [59]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [60]:
TENSOR.ndim

3

In [61]:
TENSOR.shape

torch.Size([1, 3, 3])

In [62]:
TENSOR.size()

torch.Size([1, 3, 3])

In [63]:
torch.tensor([[[1, 2, 3],
                        [3, 6, 9]]]).reshape(3,2)

tensor([[1, 2],
        [3, 3],
        [6, 9]])

In [64]:
torch.tensor([[[1, 2, 3],
                        [3, 6, 9]]]).reshape(-1,1)

tensor([[1],
        [2],
        [3],
        [3],
        [6],
        [9]])

In [65]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]], dtype=torch.float32)
TENSOR

tensor([[[1., 2., 3.],
         [3., 6., 9.],
         [2., 4., 5.]]])

In [66]:
TENSOR.dtype

torch.float32

In [67]:
y = torch.rand(2, 2)
x = torch.rand(2, 2)
x, y

(tensor([[0.6636, 0.4190],
         [0.4294, 0.9632]]),
 tensor([[0.0473, 0.9045],
         [0.2971, 0.3203]]))

### Slicing

In [68]:
x=torch.tensor([1, 2, 3, 4, 5, 6])
x[0:2]

tensor([1, 2])

In [69]:
x=torch.tensor([1, 2, 3, 4, 5, 6])
x[:2]

tensor([1, 2])

In [70]:
x=torch.tensor([1, 2, 3, 4, 5, 6])
x[-1]

tensor(6)

In [71]:
x=torch.tensor([1, 2, 3, 4, 5, 6])
x[2:]

tensor([3, 4, 5, 6])

In [72]:
# Example 2D tensor
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Syntax: x[row_slice, column_slice]

# Slice the first two rows and the first two columns
x[:2, :2]  # tensor([[1, 2],
           #         [4, 5]])

tensor([[1, 2],
        [4, 5]])

In [73]:
# Slice the second row
x[1, :]    # tensor([4, 5, 6])

tensor([4, 5, 6])

In [74]:
# Slice the third column
x[:, 2]    # tensor([3, 6, 9])

tensor([3, 6, 9])

In [75]:
# Example 2D tensor
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Get a submatrix from row 1 to 2 (exclusive of 2), and column 1 to 3
x[1:2, 1:3]  # tensor([[5, 6]])

tensor([[5, 6]])

### sum, mean, 

In [76]:
a=torch.tensor([0, 1, 1, 1])
b=torch.tensor([1, 0, 1, 1])
a.eq(b)

tensor([False, False,  True,  True])

In [77]:
# convert tensor tensor([False, False,  True,  True]) to [0, 0, 1, 1]
a.eq(b).sum()

tensor(2)

### Operation

In [78]:
x= tensor = torch.tensor([[1, 2], 
                       [3, 4]])
y= tensor = torch.tensor([[5, 6], 
                       [7, 8]])
x, y

(tensor([[1, 2],
         [3, 4]]),
 tensor([[5, 6],
         [7, 8]]))

In [79]:
x+y

tensor([[ 6,  8],
        [10, 12]])

In [80]:
z=x*y
z

tensor([[ 5, 12],
        [21, 32]])

In [81]:
# Create a tensor of values and add a number to it
# recall broadcasting rules
tensor = torch.tensor([1, 2, 3])
results= tensor + 10
results

tensor([11, 12, 13])

In [82]:
# reshaping
tensor = torch.tensor([1, 2, 3, 4, 5, 6])
tensor.view(2, 3)  # Reshape to 2x2

tensor([[1, 2, 3],
        [4, 5, 6]])

In [83]:
tensor.view(3, 2)  # Reshape to 3x2

tensor([[1, 2],
        [3, 4],
        [5, 6]])

## Comparison to NumPy Arrays
Tensors are similar to NumPy arrays but add:
- GPU support.
- Automatic differentiation (requires_grad).
 - Integration with PyTorch’s deep learning ecosystem.

In [84]:
import numpy as np
tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [85]:
numpy_array = tensor.numpy()  # To NumPy
numpy_array 

array([1, 2, 3])

In [86]:
tensor_from_numpy = torch.from_numpy(numpy_array)  # Back to tensor
tensor_from_numpy 

tensor([1, 2, 3])

### Running tensors on GPUs (and making faster computations)


In [87]:
# Check for GPU
import torch
torch.cuda.is_available()

True

In [88]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [89]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [90]:
# by default all tensors are created on the CPU,
# but you can also move them to the GPU (only if it's available )
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    x = torch.tensor([1, 2, 3])
    y = torch.tensor(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    # z = z.numpy() # not possible because numpy cannot handle GPU tenors
    # move to CPU again
    z= z.to("cpu")       # ``.to`` can also change dtype together!
    # z = z.numpy()

C:\Users\Weife\AppData\Local\Temp\ipykernel_111340\3540074575.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y = torch.tensor(x, device=device)  # directly create a tensor on GPU
