## PyTorch Fundamentals Part A

- A PyTorch tensor is a multi-dimensional array (0D to nD) that contains elements of a single data type (e.g., integers, floats). 
- Tensors are used to represent scalars, vectors, matrices, or higher-dimensional data and are optimized for mathematical operations, automatic differentiation, and GPU computation

In [43]:
import torch
torch.__version__

'2.6.0+cu126'

### Multi-dimensional

![Tensor shape](https://cdn-images-1.medium.com/max/2000/1*_D5ZvufDS38WkhK9rK32hQ.jpeg)

In [44]:
# 0D: Scalar 
x= torch.tensor(5)
x

tensor(5)

In [45]:
x.ndim

0

![shapes](https://velog.velcdn.com/images/sangyun/post/ad3a0dfa-84cd-4b29-9a4e-9768b19c6df4/image.png)
![shapes](https://velog.velcdn.com/images/sangyun/post/accfee47-0d44-401c-a6b9-c4fff5822dcf/image.png)

In [46]:
x.shape

torch.Size([])

In [47]:
x.item()

5

In [48]:
# 1D: Vector 
x=torch.tensor([1, 2, 3])
x

tensor([1, 2, 3])

In [49]:
x.ndim

1

In [50]:
# shape is a tuple, although looks like a list
x.shape

torch.Size([3])

In [51]:
# 2D Matrix
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [52]:
MATRIX.ndim

2

In [53]:
MATRIX.shape

torch.Size([2, 2])

In [54]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [55]:
TENSOR.ndim

3

In [56]:
TENSOR.shape

torch.Size([1, 3, 3])

In [57]:
TENSOR.size()

torch.Size([1, 3, 3])

In [58]:
torch.tensor([[[1, 2, 3],
                        [3, 6, 9]]]).reshape(3,2)

tensor([[1, 2],
        [3, 3],
        [6, 9]])

In [59]:
torch.tensor([[[1, 2, 3],
                        [3, 6, 9]]]).reshape(-1,1)

tensor([[1],
        [2],
        [3],
        [3],
        [6],
        [9]])

In [60]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]], dtype=torch.float32)
TENSOR

tensor([[[1., 2., 3.],
         [3., 6., 9.],
         [2., 4., 5.]]])

In [61]:
TENSOR.dtype

torch.float32

In [62]:
y = torch.rand(2, 2)
x = torch.rand(2, 2)
x, y

(tensor([[0.1741, 0.5130],
         [0.5667, 0.7953]]),
 tensor([[0.0304, 0.4022],
         [0.2714, 0.4571]]))

### Change dimensions

In [63]:
# dds a new dimension at the last position (-1 means "last axis")
# → shape changes from (3,) to (3, 1)
torch.tensor([1, 2, 3]).unsqueeze(-1) 

tensor([[1],
        [2],
        [3]])

In [64]:
# Adds a new axis at the beginning → shape changes from (3,) to (1, 3):
torch.tensor([1, 2, 3]).unsqueeze(0)

tensor([[1, 2, 3]])

In [65]:
# .squeeze() removes the dimension with size 1
# (1, 3) to (3)
torch.tensor([[1, 2, 3]]).squeeze()

tensor([1, 2, 3])

In [66]:
# # .squeeze() removes the dimension with size 1
# (3,1) to (3)
torch.tensor([[1], [2], [3]]).squeeze()

tensor([1, 2, 3])

Exapnd via broadcasting 
- a has shape (3, 1)
- b has shape (3, 4)
- a.expand_as(b) expands a to (3, 4) by repeating values along dimension 1

In [67]:
a = torch.tensor([[1], 
                  [2], 
                  [3]])   # Shape: (3, 1)
b = torch.zeros(3, 4)               # Shape: (3, 4)

a_expanded = a.expand_as(b)
print(a_expanded)
print(a_expanded.shape)  # torch.Size([3, 4])

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])
torch.Size([3, 4])


### Slicing

In [68]:
x=torch.tensor([1, 2, 3, 4, 5, 6])
x[0:2]

tensor([1, 2])

In [69]:
x=torch.tensor([1, 2, 3, 4, 5, 6])
x[:2]

tensor([1, 2])

In [70]:
x=torch.tensor([1, 2, 3, 4, 5, 6])
x[-1]

tensor(6)

In [71]:
x=torch.tensor([1, 2, 3, 4, 5, 6])
x[2:]

tensor([3, 4, 5, 6])

In [72]:
# Example 2D tensor
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Syntax: x[row_slice, column_slice]

# Slice the first two rows and the first two columns
x[:2, :2]  # tensor([[1, 2],
           #         [4, 5]])

tensor([[1, 2],
        [4, 5]])

In [73]:
# Slice the second row
x[1, :]    # tensor([4, 5, 6])

tensor([4, 5, 6])

In [74]:
# Slice the third column
x[:, 2]    # tensor([3, 6, 9])

tensor([3, 6, 9])

In [75]:
# Example 2D tensor
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Get a submatrix from row 1 to 2 (exclusive of 2), and column 1 to 3
x[1:2, 1:3]  # tensor([[5, 6]])

tensor([[5, 6]])

In [76]:
# combine multiple iterables (like lists or tuples) element-wise 
# into a single iterable of tuples.
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

for x, y in zip(a, b):
    print(x.item(), y.item())

1 4
2 5
3 6


### cat and stack
- torch.cat — Concatenate along an existing dimension
- Think: Extend an axis (like adding more rows to a table).
- Requirement: Tensors must have the same shape in all dimensions except the one you're concatenating along.

![Cat](https://user-images.githubusercontent.com/111734605/235976058-d23f9b75-401c-4547-9e17-6655f3baf957.png)


- torch.stack — Stack along a new dimension
- Think: Create a new axis (like stacking flat sheets into a pile).
- Requirement: Tensors must have exactly the same shape.



In [77]:
a = torch.tensor([[1, 2, 3],
                 [4, 5, 6]])
b = torch.tensor([[7, 8, 9],
                 [10, 11, 12]])

torch.cat([a, b], dim = 0)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [78]:
torch.cat([a, b], dim = 1)

tensor([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]])

In [79]:
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

b = torch.tensor([[7, 8, 9],
                  [10, 11, 12]])

torch.stack([a, b], dim = 0)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [80]:
# each pair of rows (from a and b) are grouped side by side along dimension 1.
# This stacks the tensors along a new dimension (dim=0).
torch.stack([a, b], dim = 1)

tensor([[[ 1,  2,  3],
         [ 7,  8,  9]],

        [[ 4,  5,  6],
         [10, 11, 12]]])

In [81]:
# This stacks along dim=2 — the last dimension, meaning the numbers from a and b are paired elementwise.
torch.stack([a, b], dim = 2)

tensor([[[ 1,  7],
         [ 2,  8],
         [ 3,  9]],

        [[ 4, 10],
         [ 5, 11],
         [ 6, 12]]])

### sum, mean, max

In [82]:
a=torch.tensor([0, 1, 1, 1])
b=torch.tensor([1, 0, 1, 1])
a.eq(b)

tensor([False, False,  True,  True])

In [83]:
# convert tensor tensor([False, False,  True,  True]) to [0, 0, 1, 1]
a.eq(b).sum()

tensor(2)

In [84]:
torch.tensor([0, 1, 2, 3]).sum()

tensor(6)

In [85]:
y=torch.tensor([0, 1, 2, 3])
torch.sum(y)

tensor(6)

In [86]:
y=torch.tensor([0, 1, 2, 3])
torch.max(y)

tensor(3)

In [87]:
test_outputs = torch.tensor([[2.5, 0.8, 1.3],  # Sample 1
                            [0.4, 3.2, 1.9]]) # Sample 2
max_values, max_indices = torch.max(test_outputs,1) # push alone the column

In [88]:
max_values

tensor([2.5000, 3.2000])

In [89]:
max_indices

tensor([0, 1])

In [90]:
test_outputs = torch.tensor([[1, 2, 3],  # Sample 1
                            [4, 5, 6]], dtype=torch.float) # Sample 2
torch.mean(test_outputs,dim=1)

tensor([2., 5.])

### Operations

In [91]:
x= tensor = torch.tensor([[1, 2], 
                       [3, 4]])
y= tensor = torch.tensor([[5, 6], 
                       [7, 8]])
x, y

(tensor([[1, 2],
         [3, 4]]),
 tensor([[5, 6],
         [7, 8]]))

In [92]:
x+y

tensor([[ 6,  8],
        [10, 12]])

In [93]:
z=x*y
z

tensor([[ 5, 12],
        [21, 32]])

In [94]:
# Create a tensor of values and add a number to it
# recall broadcasting rules
tensor = torch.tensor([1, 2, 3])
results= tensor + 10
results

tensor([11, 12, 13])

In [95]:
# reshaping
tensor = torch.tensor([1, 2, 3, 4, 5, 6])
tensor.view(2, 3)  # Reshape to 2x2

tensor([[1, 2, 3],
        [4, 5, 6]])

In [96]:
tensor.view(3, 2)  # Reshape to 3x2

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [97]:
x = torch.tensor([0, 1, 1, 0, 1, 0])
x == 1

tensor([False,  True,  True, False,  True, False])

In [98]:
y = torch.tensor([0, 1, 0, 0, 1, 1])
y == 0

tensor([ True, False,  True,  True, False, False])

In [99]:
(x == 1) & (y==0)

tensor([False, False,  True, False, False, False])

In [100]:
((x == 1) & (y==0)).sum()

tensor(1)

In [101]:
torch.sum(((x == 1) & (y==0)))

tensor(1)

## Comparison to NumPy Arrays
Tensors are similar to NumPy arrays but add:
- GPU support.
- Automatic differentiation (requires_grad).
 - Integration with PyTorch’s deep learning ecosystem.

In [102]:
import numpy as np
tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [103]:
numpy_array = tensor.numpy()  # To NumPy
numpy_array 

array([1, 2, 3])

In [104]:
tensor_from_numpy = torch.from_numpy(numpy_array)  # Back to tensor
tensor_from_numpy 

tensor([1, 2, 3])

### Running tensors on GPUs (and making faster computations)


In [105]:
# Check for GPU
import torch
torch.cuda.is_available()

True

In [106]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [107]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [108]:
# by default all tensors are created on the CPU,
# but you can also move them to the GPU (only if it's available )
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    x = torch.tensor([1, 2, 3])
    y = torch.tensor(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    # z = z.numpy() # not possible because numpy cannot handle GPU tenors
    # move to CPU again
    z= z.to("cpu")       # ``.to`` can also change dtype together!
    # z = z.numpy()

C:\Users\Weife\AppData\Local\Temp\ipykernel_87744\3540074575.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y = torch.tensor(x, device=device)  # directly create a tensor on GPU
